# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build-arm64:
    machine:
     image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: 
         command: | 
           sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
           make docker-build
      - run:
          name: Save Docker image
          command: DOCKER_IMAGE_FILENAME=image-arm64.tar make docker-save
     - persist_to_workspace:
          root: .
          paths:
            - ./image-arm64.tar
  build-amd64:
    machine:
     image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: make docker-build
      - run:
          name: Save Docker image
          command: DOCKER_IMAGE_FILENAME=image.tar make docker-save
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test-amd64:
    machine:
     image: ubuntu-1604:202004-01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Test Docker image
          command: make docker-test
  multiarch:
    machine:
     enabled: true
     image: circleci/classic:201808-01
    steps:
     - run:
          command: |
            # Turn on Experimental features
            sudo mkdir $HOME/.docker
            sudo sh -c 'echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json'
            
  publish-dockerhub:
    machine:
     enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Docker Hub
          command: make dockerhub-push
  publish-quay:
    machine:
     enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Quay.io
          command: make quay-push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-amd64
      - build-arm64
      - test:
          requires:
            - build-amd64
      - publish-dockerhub:
          requires:
            - test-amd64
      - publish-quay:
          requires:
            - test-amd64
  nightly-build-deploy:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-amd64
      - build-arm64
      - test:
          requires:
            - build-amd64
      - publish-dockerhub:
          requires:
            - test-amd64
      - publish-quay:
          requires:
            - test-amd64
