# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  docker-build-machine:
    machine:
      image: ubuntu-1604:202004-01

orbs:
  docker-buildx: foodles/docker-buildx@0.0.1
jobs:
  build:
    executor: docker-build-machine
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: make docker-build
      - run:
          name: Save Docker image
          command: DOCKER_IMAGE_FILENAME=image.tar make docker-save
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test:
    executor: docker-build-machine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Test Docker image
          command: make docker-test
  publish-dockerhub:
    executor: docker-build-machine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Docker Hub
          command: make dockerhub-push
  publish-quay:
    executor: docker-build-machine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Quay.io
          command: make quay-push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-dockerhub:
          requires:
            - test
      - publish-quay:
          requires:
            - test
  nightly-build-deploy:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-dockerhub:
          requires:
            - test
      - publish-quay:
          requires:
            - test
